version: '3.7'

services:
    db:
        image: postgres:10.1-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
    web:
        build: .
        command: python /code/Hobbes/manage.py runserver 0.0.0.0:8000
        #command: gunicorn --chdir /code/Hobbes Hobbes.wsgi
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db

volumes:
    postgres_data:
