# Generated by Django 2.2.1 on 2019-05-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicgoods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_instance',
            name='endowment',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='max_contribution',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='pot_multiplier',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='time_closed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
