# Generated by Django 2.2.1 on 2019-05-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicgoods', '0003_auto_20190505_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_instance',
            name='password',
        ),
        migrations.AddField(
            model_name='game_instance',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game_instance',
            name='instructor_password',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game_instance',
            name='user_keywork',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='instance_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='password_protected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game_response',
            name='eid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game_response',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game_response',
            name='pseudonym',
            field=models.CharField(max_length=100),
        ),
    ]
