# Generated by Django 2.2.1 on 2019-05-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicgoods', '0004_auto_20190505_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game_instance',
            old_name='user_keywork',
            new_name='user_keyword',
        ),
    ]
