# Generated by Django 2.2.1 on 2019-05-05 17:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicgoods', '0005_auto_20190505_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_response',
            name='contribution',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
