# Generated by Django 2.2.1 on 2019-05-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicgoods', '0006_auto_20190505_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_instance',
            name='instructor_password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='time_closed',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='game_instance',
            name='user_keyword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
