# Generated by Django 2.2.1 on 2019-05-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicgoods', '0007_auto_20190505_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_instance',
            name='time_closed',
        ),
    ]
